package io.github.crimix.changedprojectstask.utils;

import lombok.Data;

/**
 * Simple pair class as java does not have a built-in one
 * The getters are auto-generated by Lombok
 */
@Data
public class Pair <K, V> {
    private final K key;
    private final V value;
}
